export const CREATE_TOOL_SUCCESS = "CREATE_TOOL_SUCCESS";
export const REMOVE_TOOL_SUCCESS = "REMOVE_TOOL_SUCCESS";
export const LOAD_TOOLS_SUCCESS = "LOAD_TOOLS_SUCCESS";
export const LOAD_FILTERED_TOOLS_SUCCESS = "LOAD_FILTERED_TOOLS_SUCCESS";
